# Generated by Django 5.2.14 on 2026-05-12 21:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('transacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.transacao')),
                ('fonte', models.CharField(blank=True, max_length=120)),
                ('recorrencia', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
            bases=('finance.transacao',),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('descricao', models.TextField()),
                ('cor', models.CharField(max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='categoria_nome_not_empty'), models.CheckConstraint(condition=models.Q(('descricao', ''), _negated=True), name='categoria_descricao_not_empty'), models.CheckConstraint(condition=models.Q(('cor', ''), _negated=True), name='categoria_cor_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('transacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.transacao')),
                ('pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DINHEIRO', 'Dinheiro')], max_length=10)),
                ('num_parcelas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('parcela_atual', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to='finance.categoria')),
            ],
            options={
                'verbose_name': 'Parcelamento',
                'verbose_name_plural': 'Parcelamentos',
            },
            bases=('finance.transacao',),
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('transacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='finance.transacao')),
                ('pagamento', models.CharField(choices=[('PIX', 'PIX'), ('CREDITO', 'Crédito'), ('DEBITO', 'Débito'), ('DINHEIRO', 'Dinheiro')], max_length=10)),
                ('tipo_gasto', models.CharField(choices=[('FIXO', 'Fixo'), ('VARIAVEL', 'Variável')], max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='finance.categoria')),
            ],
            options={
                'verbose_name': 'Saída',
                'verbose_name_plural': 'Saídas',
            },
            bases=('finance.transacao',),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='transacao_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transacao',
            constraint=models.CheckConstraint(condition=models.Q(('nome', ''), _negated=True), name='transacao_nome_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='parcelamento',
            constraint=models.CheckConstraint(condition=models.Q(('num_parcelas__gte', 1)), name='parcelamento_num_parcelas_min1'),
        ),
        migrations.AddConstraint(
            model_name='parcelamento',
            constraint=models.CheckConstraint(condition=models.Q(('parcela_atual__gte', 1)), name='parcelamento_parcela_atual_min1'),
        ),
        migrations.AddConstraint(
            model_name='parcelamento',
            constraint=models.CheckConstraint(condition=models.Q(('valor_parcela__gt', 0)), name='parcelamento_valor_parcela_positivo'),
        ),
    ]
