# Generated by Django 5.2.14 on 2026-05-12 23:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='extra_unico_por_dia'), models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='extra_valor_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='LimiteDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('limite_calculado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('limite_ajustado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gasto_dia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='limite_diario_unico_por_dia'), models.CheckConstraint(condition=models.Q(('limite_calculado__gte', 0)), name='limite_calculado_nao_negativo'), models.CheckConstraint(condition=models.Q(('gasto_dia__gte', 0)), name='gasto_dia_nao_negativo')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reserva', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='reserva_saldo_nao_negativo')],
            },
        ),
    ]
