# Generated by Django 5.2.14 on 2026-05-13 01:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_extra_limitediario_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoDiario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('dentro_limite', models.BooleanField(default=False)),
                ('usou_reserva', models.BooleanField(default=False)),
                ('usou_extra', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_diarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'data'), name='progresso_diario_unico_por_dia')],
            },
        ),
    ]
