# Generated by Django 5.2.14 on 2026-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_progressodiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamento',
            name='antecipadas_no_ciclo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parcelamento',
            name='ciclo_referencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
